<?php
return [
    [
        "id" => 1,
        "package-id" => "complete-chardham-yatra",
        "package-image" => "images/destination/kedarnath.png",
        "package-title" => "Complete Char Dham Yatra Package",
        "package-duration" => "9 Nights | 10 Days",
        "package-offer" => "25% OFF",
        "package-attraction" => [
            "Comfortable Hotel Stay",
            "Breakfast & Dinner",
            "Private Cab for Entire Tour",
            "Yamunotri, Gangotri, Kedarnath & Badrinath Darshan",
            "All Toll Taxes & Parking Charges",
        ],
        "package-price" => "On Request",
        "package-destinations" => ["Yamunotri", "Gangotri", "Kedarnath", "Badrinath", "Haridwar", "Rishikesh"],
    ],
    [
        "id" => 2,
        "package-id" => "dodham-yatra",
        "package-image" => "images/destination/badrinath.png",
        "package-title" => "Do Dham Yatra (Kedarnath & Badrinath)",
        "package-duration" => "5 Nights | 6 Days",
        "package-offer" => "25% OFF",
        "package-attraction" => [
            "Comfortable Hotel Stay",
            "Breakfast & Dinner",
            "Private Cab for Entire Tour",
            "Kedarnath & Badrinath Darshan",
            "All Toll Taxes & Parking Charges",
        ],
        "package-price" => "On Request",
        "package-destinations" => ["Kedarnath", "Badrinath", "Guptkashi", "Haridwar", "Rishikesh"],
    ],
    [
        "id" => 3,
        "package-id" => "Kedarnath-tour",
        "package-image" => "images/destination/kedarnath.png",
        "package-title" => "Kedarnath Tour Package",
        "package-duration" => "3 Nights | 4 Days",
        "package-offer" => "20% OFF",
        "package-attraction" => [
           "Comfortable Hotel Stay",
            "Breakfast & Dinner",
            "Private Cab for Entire Tour",
            "Kedarnath Temple Darshan",
            "All Toll Taxes & Parking Charges",
        ],
        "package-price" => "On Request",
        "package-destinations" => ["Haridwar", "Rishikesh", "Guptkashi", "Sonprayag", "Kedarnath"],
    ],
        [
        "id" => 4,
        "package-id" => "yamunotri-dham",
        "package-image" => "images/destination/yamunotri-dham.png",
        "package-title" => "Yamunotri Dham Tour From Haridwar",
        "package-duration" => "2 Nights | 3 Days",
        "package-offer" => "20% OFF",
        "package-attraction" => [
            "Comfortable Hotel Stay",
            "Breakfast & Dinner",
            "Private Cab for Entire Tour",
            "Yamunotri Dham Darshan",
            "All Toll Taxes & Parking Charges",
        ],
        "package-price" => "On Request",
        "package-destinations" => ["Haridwar", "Dehradun", "Barkot", "Yamunotri"],
    ],
    [
        "id" => 5,
        "package-id" => "gangotri-dham",
        "package-image" => "images/destination/gangotri-dham.png",
        "package-title" => "Gangotri Dham Tour From Haridwar",
        "package-duration" => "2 Nights | 3 Days",
        "package-offer" => "20% OFF",
        "package-attraction" => [
            "Comfortable Hotel Stay",
            "Breakfast & Dinner",
            "Private Cab for Entire Tour",
            "Gangotri Temple Darshan",
            "All Toll Taxes & Parking Charges",
        ],
        "package-price" => "On Request",
        "package-destinations" => ["Gangotri", "Uttarkashi", "Haridwar"],
    ],
    [
        "id" => 6,
        "package-id" => "haridwar-rishikesh",
        "package-image" => "images/destination/rishikesh.jpg",
        "package-title" => "Haridwar Rishikesh Spiritual Tour",
        "package-duration" => "3 Nights / 4 Days",
        "package-offer" => "10% OFF",
        "package-attraction" => [
        "Comfortable Hotel Stay",
        "Daily Breakfast & Dinner",
        "Private Transportation",
        "Haridwar & Rishikesh Sightseeing",
        "Experienced Tour Assistance",
        "All Toll Taxes & Parking",
    ],
        "package-price" => "On Request",
        "package-destinations" => ["haridwar", "Rishikesh",],
    ]
];
?>